# 一、Tensor(张量)

Tensors 类似于 NumPy 的 ndarrays ，同时 Tensors 可以使用 GPU 进行计算。

构造一个矩阵，不初始化

In [2]:
import torch

In [3]:
torch.empty(5,3)

tensor([[1.0194e-38, 9.0919e-39, 8.4490e-39],
        [1.0653e-38, 9.9184e-39, 8.4490e-39],
        [8.9082e-39, 9.8265e-39, 1.0194e-38],
        [1.0286e-38, 1.0653e-38, 8.7245e-39],
        [9.6429e-39, 9.6429e-39, 8.7245e-39]])

构造一个随机初始化矩阵

In [4]:
torch.rand(5,3)

tensor([[0.7509, 0.1071, 0.5691],
        [0.2419, 0.6261, 0.0673],
        [0.4487, 0.9398, 0.0803],
        [0.3840, 0.8271, 0.4332],
        [0.8078, 0.7181, 0.7026]])

构造一个全为 0的矩阵，而且数据类型是 long

In [5]:
torch.zeros(5,3,dtype = torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

构造一个张量，直接使用数据

In [6]:
torch.tensor([4.5,8.5])

tensor([4.5000, 8.5000])

创建一个tensor基于已经存在的tensor

In [7]:
x  = torch.ones(5,3,dtype = torch.double)

In [8]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.rand_like(x)

In [10]:
x

tensor([[0.9626, 0.8233, 0.6616],
        [0.8559, 0.5709, 0.7780],
        [0.6273, 0.7594, 0.4075],
        [0.7823, 0.8394, 0.9765],
        [0.5441, 0.6275, 0.9498]], dtype=torch.float64)

获取维度信息

In [11]:
x.size()

torch.Size([5, 3])

加法操作一

In [12]:
y = torch.rand(5,3)
y

tensor([[0.5881, 0.5964, 0.2382],
        [0.2500, 0.6582, 0.4103],
        [0.1620, 0.8828, 0.5490],
        [0.3628, 0.5562, 0.8887],
        [0.0085, 0.0150, 0.9286]])

In [13]:
x+y

tensor([[1.5507, 1.4197, 0.8998],
        [1.1058, 1.2291, 1.1883],
        [0.7892, 1.6423, 0.9564],
        [1.1451, 1.3956, 1.8653],
        [0.5526, 0.6425, 1.8784]], dtype=torch.float64)

加法操作二

In [14]:
torch.add(x,y)

tensor([[1.5507, 1.4197, 0.8998],
        [1.1058, 1.2291, 1.1883],
        [0.7892, 1.6423, 0.9564],
        [1.1451, 1.3956, 1.8653],
        [0.5526, 0.6425, 1.8784]], dtype=torch.float64)

加法操作三

In [15]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
result

tensor([[1.5507, 1.4197, 0.8998],
        [1.1058, 1.2291, 1.1883],
        [0.7892, 1.6423, 0.9564],
        [1.1451, 1.3956, 1.8653],
        [0.5526, 0.6425, 1.8784]])

追加

In [46]:
y.add_(x)
y

tensor([[2.5133, 2.2430, 1.5614],
        [1.9617, 1.8001, 1.9664],
        [1.4165, 2.4017, 1.3639],
        [1.9274, 2.2349, 2.8418],
        [1.0967, 1.2700, 2.8282]])

相乘

In [55]:
a = torch.rand(2,2)
b = torch.ones(2,2)
torch.mm(a,b),torch.matmul(a,b),a@b

(tensor([[0.4596, 0.4596],
         [0.2885, 0.2885]]),
 tensor([[0.4596, 0.4596],
         [0.2885, 0.2885]]),
 tensor([[0.4596, 0.4596],
         [0.2885, 0.2885]]))

索引切片操作

In [17]:
y[:,1]

tensor([1.4197, 1.2291, 1.6423, 1.3956, 0.6425])

In [18]:
n = torch.rand(2,3,28,28)
print(n[0].shape)
print(n[0,0].shape)
print(n[0,0,27,2])

torch.Size([3, 28, 28])
torch.Size([28, 28])
tensor(0.0375)


间隔切片

In [19]:
n[:,:,::2,::2].shape

torch.Size([2, 3, 14, 14])

In [20]:
n.index_select(1,torch.tensor([0,1])).shape

torch.Size([2, 2, 28, 28])

In [21]:
n[...].shape

torch.Size([2, 3, 28, 28])

In [22]:
n[:,2,...].shape

torch.Size([2, 28, 28])

tensor维度变换

view/reshape 维度变换

In [23]:
n = torch.randn(4,1,28,28)
n.shape

torch.Size([4, 1, 28, 28])

In [24]:
n.view(4,28*28)

tensor([[ 0.3845,  1.3457, -0.7197,  ...,  0.2859,  1.2775,  0.5653],
        [-1.8319,  0.0745, -0.2538,  ..., -0.6842, -0.0268,  1.2643],
        [ 0.0636, -0.6901,  1.5690,  ...,  0.7547, -0.2170,  1.5236],
        [-0.8973, -0.1512,  0.4184,  ...,  0.0297,  0.0848,  0.4867]])

In [25]:
n.view(4*28,28)

tensor([[ 0.3845,  1.3457, -0.7197,  ...,  0.6411, -1.4169, -1.7104],
        [ 1.1215, -1.2764, -0.2309,  ..., -1.4323, -1.3481,  0.1404],
        [ 0.1478,  1.7759,  1.1545,  ..., -0.1460, -0.9927, -1.2620],
        ...,
        [ 0.9254,  0.9192,  2.1133,  ...,  1.2068, -0.7410, -0.7643],
        [-0.3588, -1.5650,  0.4849,  ...,  1.5515,  0.7355,  0.0147],
        [ 0.9809,  0.0433, -0.5398,  ...,  0.0297,  0.0848,  0.4867]])

squeeze/unsqueeze 维度增加与减少

In [26]:
n.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [27]:
n.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [28]:
n.squeeze().shape

torch.Size([4, 28, 28])

In [29]:
n.squeeze(-1).shape

torch.Size([4, 1, 28, 28])

Expand/repeat 维度扩展

In [30]:
m = torch.randn(1,1,28,1)
m.shape
m.expand(4,1,28,28).shape

torch.Size([4, 1, 28, 28])

In [31]:
m.repeat(4,1,4,4).shape

torch.Size([4, 1, 112, 4])

矩阵变换

.t    矩阵转置

In [32]:
m = torch.randn(4,3)
m.t().shape

torch.Size([3, 4])

使用 .item() 来获得这个 value

In [33]:
a = torch.randn(1)
a.item()

1.4097188711166382

合并与分割

cat

In [35]:
a = torch.rand(4,32,8)

In [36]:
b = torch.rand(5,32,8)

In [37]:
torch.cat([a,b],dim = 0).shape

torch.Size([9, 32, 8])

stack

In [39]:
c = torch.randn(4,32,8)
torch.stack([a,c],dim = 1).shape

torch.Size([4, 2, 32, 8])

split:by len

In [42]:
aa,bb = c.split(2,dim = 0)
aa.shape,bb.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

In [43]:
aa,bb = c.split([3,1],dim = 0)
aa.shape,bb.shape

(torch.Size([3, 32, 8]), torch.Size([1, 32, 8]))

shunk:by num

In [45]:
aa,bb = c.chunk(2,dim = 0)
aa.shape,bb.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

统计属性

norm范数 mean,min,max,sum,prod(累乘) argmax,argmin

In [58]:
a = torch.full([8],1,dtype = torch.float)
b = a.view(2,4)
c = a.view(2,2,2)

In [59]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [60]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

# 二、自动微分

创建一个张量，设置 requires_grad=True 来跟踪与它相关的计算

In [39]:
x = torch.ones(2,2,requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [40]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

y 作为操作的结果被创建，所以它有 grad_fn

In [41]:
y.grad_fn

In [43]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_( … ) 会改变张量的 requires_grad 标记。输入的标记默认为 False ，如果没有提供
相应的参数。

In [44]:
a = torch.randn(2,2)
a = ((a * 3)/(a - 1))
print(a.requires_grad)

False


In [45]:
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

True


梯度

In [46]:
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])